name: Build and Push

on:
  push:
    branches: [ main ]

jobs:
  build:
    uses: team-redbull/.github/.github/workflows/ghcr-build-push.yml@main
    with:
      image-name: segments-manager
      helm-values-path: deploy/helm/values.yaml
    secrets: inherit
